name: example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
    - name:  checkout
      uses: actions/checkout@v4

    - name: configure
      run: | 
        echo $(ls -l)
        echo "hello v2"
        echo $(git diff --name-only  "*.sql") 
        pip install -r requirements.txt

      - name: goodbye
        echo "goodby!"
