name: example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name:  checkout
      uses: actions/checkout@v4

    - name: configure
      run: | 
        ls -l
        echo "hello"
        pip install pandas
