name: example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name:  checkout
      uses: actions/checkout@v4

    - name: configure
      run: | 
        echo $(ls -l)
        echo "hello"
        echo $(git diff --name-only  "*.sql") 
        pip install -r requirements.txt
        sqlfluff lint ./sql/test.sql --dialect bigquery
